const eventos = [

    {
        "image": "https://s1.ticketm.net/dam/a/3f2/bfc6672f-ac80-4e3a-98a4-db4d9d9133f2_1687811_TABLET_LANDSCAPE_3_2.jpg",
        "name": "Diego Torres - Festival Starlite",
        "descripcion": "Adquiere tus entradas para el concierto de Diego Torres - Festival Starlite",
        "id": "Z698xZ2qZa6IW",
        "title": "Diego Torres - Festival Starlite",
        "time": "22:00:00",
        "date": "2022-08-12",
        "status": "onsale",
        "priceMin": 20,
        "priceMax": 44.73,
        "genrename": "Pop",
        "Location": "Auditorio Starlite",
        "city": "Marbella",
        "address": "Calle Albinoni, s/n. Cantera de Nagüeles, 29602 Marbella, España",
        "category": "Festivales",
        "url": "https://www.ticketmaster.es/event/diego-torres-festival-starlite-tickets/31293?language=en-us"
    },
    {
        "image": "https://s1.ticketm.net/dam/a/260/462e2630-ca6e-467e-9d49-f4bcf154b260_1649691_CUSTOM.jpg",
        "name": "Jorge Drexler & Coque Malla - Festival Starlite",
        "descripcion": "Adquiere tus entradas para el concierto de Jorge Drexler & Coque Malla - Festival Starlite",
        "id": "Z698xZ2qZa6rL",
        "title": "Jorge Drexler & Coque Malla - Festival Starlite",
        "time": "22:00:00",
        "date": "2022-08-13",
        "status": "onsale",
        "priceMin": 22.73,
        "priceMax": 59.09,
        "genrename": "Rock",
        "Location": "Auditorio Starlite",
        "city": "Marbella",
        "address": "Calle Albinoni, s/n. Cantera de Nagüeles, 29602 Marbella, España",
        "category": "Festivales",
        "url": "https://www.ticketmaster.es/event/jorge-drexler--coque-malla-festival-starlite-tickets/30623?language=en-us"
    },
    {
        "image": "https://s1.ticketm.net/dam/a/b2f/8b6be8fb-c563-43a5-b40d-07577b654b2f_1510231_CUSTOM.jpg",
        "name": "Andrea Bocelli - Festival Starlite",
        "descripcion": "Adquiere tus entradas para el concierto de Andrea Bocelli - Festival Starlite",
        "id": "Z698xZ2qZakzg",
        "title": "Andrea Bocelli - Festival Starlite",
        "time": "22:00:00",
        "date": "2022-08-15",
        "status": "onsale",
        "priceMin": 177.27,
        "priceMax": 434.55,
        "genrename": "Opera",
        "Location": "Auditorio Starlite",
        "city": "Marbella",
        "address": "Calle Albinoni, s/n. Cantera de Nagüeles, 29602 Marbella, España",
        "category": "Festivales",
        "url": "https://www.ticketmaster.es/event/andrea-bocelli-festival-starlite-tickets/28213?language=en-us"
    },
    {
        "image": "https://s1.ticketm.net/dam/a/4c6/9468f0e0-6f4e-4158-acf0-c3c4501774c6_1591651_RECOMENDATION_16_9.jpg",
        "name": "Ballet Flamenco Sara Baras - Festival Starlite",
        "descripcion": "Adquiere tus entradas para el concierto de Ballet Flamenco Sara Baras - Festival Starlite",
        "id": "Z698xZ2qZa6u_",
        "title": "Ballet Flamenco Sara Baras - Festival Starlite",
        "time": "22:00:00",
        "date": "2022-08-16",
        "status": "onsale",
        "priceMin": 30.91,
        "priceMax": 75.45,
        "genrename": "Flamenco",
        "Location": "Auditorio Starlite",
        "city": "Marbella",
        "address": "Calle Albinoni, s/n. Cantera de Nagüeles, 29602 Marbella, España",
        "category": "Festivales",
        "url": "https://www.ticketmaster.es/event/ballet-flamenco-sara-baras-festival-starlite-tickets/29529?language=en-us"
    },


    {
        "image": "https://s1.ticketm.net/dam/a/f33/58c7d09f-304d-4c08-88d4-7f3d31c76f33_1681371_RETINA_LANDSCAPE_16_9.jpg",
        "name": "Farruquito y Arcangel - Festival Starlite",
        "descripcion": "Adquiere tus entradas para el concierto de Farruquito y Arcangel - Festival Starlite",
        "id": "Z698xZ2qZa6Jt",
        "title": "Farruquito y Arcangel - Festival Starlite",
        "time": "22:00:00",
        "date": "2022-08-19",
        "status": "onsale",
        "priceMin": 20,
        "priceMax": 45.45,
        "genrename": "Flamenco",
        "Location": "Auditorio Starlite",
        "city": "Marbella",
        "address": "Calle Albinoni, s/n. Cantera de Nagüeles, 29602 Marbella, España",
        "category": "Festivales",
        "url": "https://www.ticketmaster.es/event/farruquito-y-arcangel-festival-starlite-tickets/31145?language=en-us"
    },

  
    {
        "image": "https://s1.ticketm.net/dam/a/b21/ddd0398a-d821-45b7-bfe8-539aa145db21_1658851_RETINA_PORTRAIT_16_9.jpg",
        "name": "Luis Fonsi - Festival Starlite",
        "descripcion": "Adquiere tus entradas para el concierto de Luis Fonsi - Festival Starlite",
        "id": "Z698xZ2qZa6Ov",
        "title": "Luis Fonsi - Festival Starlite",
        "time": "22:00:00",
        "date": "2022-08-22",
        "status": "onsale",
        "priceMin": 45.46,
        "priceMax": 134.72,
        "genrename": "Pop",
        "Location": "Auditorio Starlite",
        "city": "Marbella",
        "address": "Calle Albinoni, s/n. Cantera de Nagüeles, 29602 Marbella, España",

        "category": "Festivales",
        "url": "https://www.ticketmaster.es/event/luis-fonsi-festival-starlite-tickets/30721?language=en-us"
    },
    {
        "image": "https://s1.ticketm.net/dam/a/822/dde15ec6-6688-4236-8b0d-74aa29027822_1567041_RETINA_LANDSCAPE_16_9.jpg",
        "name": "Dani Martín - Festival Starlite",
        "descripcion": "Adquiere tus entradas para el concierto de Dani Martín - Festival Starlite",
        "id": "Z698xZ2qZa6d6",
        "title": "Dani Martín - Festival Starlite",
        "time": "22:00:00",
        "date": "2022-08-23",   
        "status": "onsale",
        "priceMin": 51.82,
        "priceMax": 131.01,
        "genrename": "Pop",
        "Location": "Auditorio Starlite",
        "city": "Marbella",
        "address": "Calle Albinoni, s/n. Cantera de Nagüeles, 29602 Marbella, España",

        "category": "Festivales",
    
        "url": "https://www.ticketmaster.es/event/dani-martin-festival-starlite-tickets/28871?language=en-us"
    },


    {
        "image": "https://s1.ticketm.net/dam/a/7bd/6063bf0e-dcfa-4615-ad58-4fbd62e3e7bd_1657941_CUSTOM.jpg",
        "name": "Morat - Festival Starlite",
        "descripcion": "Adquiere tus entradas para el concierto de Morat - Festival Starlite",
        "id": "Z698xZ2qZa60M",
        "title": "Morat - Festival Starlite",
        "time": "22:00:00",
        "date": "2022-08-30",
        "status": "onsale",
        "priceMin": 40,
        "priceMax": 79.09,
        "genrename": "Rock",
        "Location": "Auditorio Starlite",
        "city": "Marbella",
        "address": "Calle Albinoni, s/n. Cantera de Nagüeles, 29602 Marbella, España",
        "category": "Festivales",
        "url": "https://www.ticketmaster.es/event/morat-festival-starlite-tickets/31031?language=en-us"
    },

    

    {
        "image": "https://s1.ticketm.net/dam/a/c20/4af9c733-9cb8-4803-a2d5-4b5251d14c20_1551221_TABLET_LANDSCAPE_LARGE_16_9.jpg",
        "name": "Estopa - Festival Starlite",
        "descripcion": "Adquiere tus entradas para el concierto de Estopa - Festival Starlite",
        "id": "Z698xZ2qZakTt",
        "title": "Estopa - Festival Starlite",
        "time": "22:00:00",
        "date": "2022-09-03",
        "status": "onsale",
        "priceMin": 60.91,
        "priceMax": 112.73,
        "genrename": "Rock",
        "Location": "Auditorio Starlite",
        "city": "Marbella",
        "address": "Calle Albinoni, s/n. Cantera de Nagüeles, 29602 Marbella, España",
        "category": "Festivales",
        "url": "https://www.ticketmaster.es/event/estopa-festival-starlite-tickets/28649?language=en-us"
    },
    {
        "image": "https://s1.ticketm.net/dam/a/382/13e36aef-7e31-4b3e-85cb-45d197308382_1640991_RETINA_PORTRAIT_3_2.jpg",
        "name": "Anastacia - Festival Starlite",
        "descripcion": "Adquiere tus entradas para el concierto de Anastacia - Festival Starlite",
        "id": "Z698xZ2qZa68E",
        "title": "Anastacia - Festival Starlite",
        "time": "22:00:00",
        "date": "2023-07-12",
        "status": "rescheduled",
        "priceMin": 27.99,
        "priceMax": 83.46,
        "genrename": "Rock",
        "Location": "Auditorio Starlite",
        "city": "Marbella",
        "address": "Calle Albinoni, s/n. Cantera de Nagüeles, 29602 Marbella, España",
         "category": "Festivales",
        "url": "https://www.ticketmaster.es/event/anastacia-festival-starlite-tickets/29735?language=en-us"
    },
    {
        "image": "https://s1.ticketm.net/dam/a/939/beb7171b-8055-4a48-8223-92449c968939_1666351_RETINA_LANDSCAPE_16_9.jpg",
        "name": "Rosalía: MOTOMAMI WORLD TOUR",
        "descripcion": "Adquiere tus entradas para el concierto de Rosalía: MOTOMAMI WORLD TOUR",
        "id": "Z698xZ2qZa6rD",
        "title": "Rosalía: MOTOMAMI WORLD TOUR",
        "time": "21:30:00",
        "date": "2022-07-29",
        "status": "onsale",
        "priceMin": 59,
        "priceMax": 136.5,
        "genrename": "Urban",
        "Location": "WiZink Center",
        "city": "Madrid",
        "address": "Av. Felipe II, s/n",
        "category": "Conciertos",
        "url": "https://www.ticketmaster.es/event/rosalia-motomami-world-tour-tickets/30651?language=en-us"
    },



    {
        "image": "https://s1.ticketm.net/dam/a/d8e/5432bf7a-0f5e-4b47-8b7d-177892dd2d8e_1464461_RETINA_PORTRAIT_3_2.jpg",
        "name": "Limp Bizkit",
        "descripcion":"Compra tus entradas para LimpBizkit",
        "id": "Z698xZ2qZaAl9",
        "date": "2022-08-24",
        "time": "19:00:00",
        "status": "rescheduled",
        "genrename": "Rock",
        "priceMin": 50.0,
        "priceMax": 58.0,
        "Location": "WiZink Center",
        "city": "Madrid",
        "address": "Av. Felipe II, s/n",
        "category": "Conciertos",
        "url": "https://www.ticketmaster.es/event/limp-bizkit-tickets/23255?language=en-us",
    },
    {
        "name": "Mon Laferte",
        "id": "Z698xZ2qZa6E6",
        "descripcion": "concierto",
        "url": "https://www.ticketmaster.es/event/mon-laferte-tickets/31175?language=en-us",
        "image": "https://s1.ticketm.net/dam/a/c9d/29f60a38-5790-44d8-9166-84a625031c9d_1669771_RETINA_PORTRAIT_3_2.jpg",
        "date": "2022-09-03",
        "status": "onsale",
        "time": "21:30:00",
        "genrename": "Pop",
        "priceMin": 32.0,
        "priceMax": 32.0,
        "Location": "Sala Moon",
        "city": "Valencia",
        "country": "España",
        "address": "Carrer de Sant Vicent Màrtir, 200",
       "category": "Conciertos",
    },
    {   
        
        "name": "Muse",
        "id": "Z698xZ2q235E6",
        "descripcion": " Muse repasará los éxitos de su carrera y adelantará algunas de las nuevas canciones de su esperadísimo noveno álbum en estudio Will Of The People que verá la luz el 26 de agosto.",
        "url": "https://www.ticketmaster.es/event/muse-tickets/31931?language   =es-es",
        "image": "https://s1.ticketm.net/img/tat/dam/a/6e4/ee7b835f-6caf-48e7-9958-d766e0f656e4_1749681_CUSTOM.jpg",
        "date": "2022-09-08",
        "status": "onsale",
        "time": "22:15:00",
        "genrename": "Rock",
        "priceMin": 73.50,
        "priceMax": 73.50,
        "Location": "Estadio Abanca Balaídos",
        "city": "Vigo",
        "country": "España",
        "address": "Av. de Balaídos, s/n, 36210 Vigo, España",
       "category": "Conciertos",
    },
    {
        "image":"https://s1.ticketm.net/img/tat/dam/a/23f/464ff41c-1fc6-4276-b8f4-d07e0599923f_1633501_CUSTOM.jpg",
        "name": "Sigur Rós",
        "id": "Z698xZ2q23126",
        "descripcion":" Los islandeses, además de repasar los éxitos de sus 25 años de carrera, presentarán algunas de las canciones del que será su nuevo álbum",
        "date": "2022-09-29",
        "status": "onsale",
        "time": "21:00.00",
        "priceMin": 56.50,
        "priceMax": 56.50,
        "genrename": "Rock",
        "Location": "WiZink Center",
        "city": "Madrid",
        "address": "Av. Felipe II, s/n",
        "category": "Conciertos",
        "url":"https://www.ticketmaster.es/event/sigur-ros-entradas/30013"
            
    }
    
    

]



export default eventos